ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-RR';

DROP TABLE PAYMENT;
DROP TABLE ORDER;
DROP TABLE SHIPMENT;
DROP TABLE SHIPMENTLINE;

CREATE TABLE PAYMENT (
 PAYMENTNUMBER              NUMBER(10) NOT NULL,
 PAYDATE                    DATE,
 PAYMENTMETHOD              VARCHAR2(13),
 TOTALAMOUNT                NUMBER(10,2),
 ORDERNUMBER                NUMBER(5),
 CONSTRAINT PAYMENTMETHOD_CK CHECK (PAYMENTMETHOD IN ('CH', 'CC')));

ALTER TABLE PAYMENT ADD (
 CONSTRAINT PAYMENTNUMBER_PK PRIMARY KEY (PAYMENTNUMBER),
 CONSTRAINT ORDERNUMBER_FK   FOREIGN KEY (ORDERNUMBER) REFERENCES ORDER (ORDERNUMBER));

CREATE TABLE ORDER (
 ORDERNUMBER               NUMBER(5) NOT NULL,
 ORDERDATE                 DATE,
 ORDERSOURCEID             VARCHAR2(5),
 CUSTOMERNUMBER            NUMBER(5));

ALTER TABLE ORDER ADD (
 CONSTRAINT ORDERNUMBER_PK   PRIMARY KEY (ORDERNUMBER),
 CONSTRAINT ORDERSOURCEID_FK FOREIGN KEY (ORDERSOURCEID) REFERENCES ORDERSOURCE (ORDERSOURCEID),
 CONSTRAINT CUSTOMERNUMBER   FOREIGN KEY (CUSTOMERNUMBER) REFERENCES CUSTOMER (CUSTOMERNUMBER));

CREATE TABLE SHIPMENT (
 SHIPMENTID               NUMBER(5),
 EXPECTEDDATE             DATE,
 ORDERNUMBER              NUMBER(5));

 ALTER TABLE SHIPMENT ADD(
 CONSTRAINT SHIPMENTID_PK  PRIMARY KEY (SHIPMENTID),
 CONSTRAINT ORDERNUMBER_FK FOREIGN KEY (ORDERNUMBER) REFERENCES ORDER (ORDERNUMBER),
 );

CREATE TABLE SHIPMENTLINE (
 SHIPMENTID               NUMBER(5),
 INVENTORYNUMBER          NUMBER(10),
 QUANTITYSHIPPED          NUMBER(3),
 DATERECEIVED             DATE,
 CONSTRAINT QTYSHIPED_CK CHECK (QUANTITYSHIPPED > 0));

 ALTER TABLE SHIPMENTLINE ADD(
 CONSTRAINT SHIPMENTID_INVENTORYNUM_PK PRIMARY KEY (SHIPMENTID, INVENTORYNUMBER),
 CONSTRAINT SHIPMENTID_FK              FOREIGN KEY (SHIPMENTID)      REFERENCES SHIPMENT (SHIPMENTID),
 CONSTRAINT INVENTORYNUMBER_FK         FOREIGN KEY (INVENTORYNUMBER) REFERENCES INVENTORY (INVENTORYNUMBER));

-- Insert Statement for the tables 

INSERT INTO PAYMENT (PAYMENTNUMBER, PAYDATE, PAYMENTMETHOD, TOTALAMOUNT, ORDERNUMBER) VALUES (10,'ACCOUNTING','NEW YORK', 11 , 11);
INSERT INTO PAYMENT (PAYMENTNUMBER, PAYDATE, PAYMENTMETHOD, TOTALAMOUNT, ORDERNUMBER) VALUES (20,'RESEARCH','DALLAS', 11, 11);
INSERT INTO PAYMENT (PAYMENTNUMBER, PAYDATE, PAYMENTMETHOD, TOTALAMOUNT, ORDERNUMBER) VALUES (30,'SALES','CHICAGO', 11, 11);

INSERT INTO ORDER (ORDERNUMBER, ORDERDATE, ORDERSOURCEID, CUSTOMERNUMBER) VALUES (7839,'KING','PRESIDENT',NULL);
INSERT INTO ORDER (ORDERNUMBER, ORDERDATE, ORDERSOURCEID, CUSTOMERNUMBER) VALUES (7698,'BLAKE','MANAGER',7839);
INSERT INTO ORDER (ORDERNUMBER, ORDERDATE, ORDERSOURCEID, CUSTOMERNUMBER) VALUES (7782,'CLARK','MANAGER',7839);

INSERT INTO SHIPMENT (SHIPMENTID, EXPECTEDDATE, ORDERNUMBER) VALUES (11, '', 11);
INSERT INTO SHIPMENT (SHIPMENTID, EXPECTEDDATE, ORDERNUMBER) VALUES (11, '', 11);
INSERT INTO SHIPMENT (SHIPMENTID, EXPECTEDDATE, ORDERNUMBER) VALUES (11, '', 11);

INSERT INTO SHIPMENTLINE (SHIPMENTID, INVENTORYNUMBER, QUANTITYSHIPPED, DATERECEIVED) VALUES (1,700,1200, '');
INSERT INTO SHIPMENTLINE (SHIPMENTID, INVENTORYNUMBER, QUANTITYSHIPPED, DATERECEIVED) VALUES (1,700,1200, '');
INSERT INTO SHIPMENTLINE (SHIPMENTID, INVENTORYNUMBER, QUANTITYSHIPPED, DATERECEIVED) VALUES (1,700,1200, '');




